name: Go Build
on:
  push:
    tags:
      - '*.*.*'
jobs:
  buildAndDeploy:
    runs-on:  ubuntu-latest
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
          - goarch: arm64
            goos: linux
          - goarch: amd64
            goos: darwin
          - goarch: arm64
            goos: darwin
          - goarch: amd64
            goos: windows
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 'latest'
    - run: go version
    - name: make
      run: make
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
    - name: Packaging...
      run: tar czf traffic-consume-${{ matrix.goos }}-${{ matrix.goarch }}.tgz traffic-consume
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GOACTION }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Release
        draft: false
        prerelease: false
    - name: Uploading assets...
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GOACTION }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./traffic-consume-${{ matrix.goos }}-${{ matrix.goarch }}.tgz
        asset_name: traffic-consume-${{ matrix.goos }}-${{ matrix.goarch }}.tgz
        asset_content_type: application/gzip
